@startuml

skinparam backgroundColor white
skinparam classBorderColor black
skinparam classBackgroundColor white
skinparam ArrowColor black
skinparam defaultFontColor black

class SumAction {
    + new(value)
    + add_value(acc, value)
    + get_result(acc)
}

class MaxAction {
    + new(value)
    + add_value(acc, value)
    + get_result(acc)
}

class AvgAction {
    + new(value)
    + add_value(acc, value)
    + get_result(acc)
}

RowAggregator *-- ColumnActionAggregator

ColumnActionAggregator <|-- SumAction
ColumnActionAggregator <|-- MaxAction
ColumnActionAggregator <|-- AvgAction

abstract class ColumnActionAggregator {
    + new(value)
    + add_value(acc, value)
    + get_result(acc)
}

class RowAggregator {
    - group_actions
    - count_out_fields
    + new_group_acc(row)
    + add_group_acc(acc, row)
    + add_aggregated_to(base, acc)
    + iterate_rows(acc)
}

@enduml