@startuml

skinparam backgroundColor white
skinparam classBorderColor black
skinparam classBackgroundColor white
skinparam ArrowColor black
skinparam defaultFontColor black

class KeepAllRowsAction {
    + add_new(current_grouped, row)
    + add_to(current_grouped, row)
    + add_all(current_grouped, rows)
}

class KeepTopAction {
    - comp_key
    + add_new(current_grouped, row)
    + add_to(current_grouped, row)
    + add_all(current_grouped, rows)
}

class KeepTopKAction {
    - comp_key
    - limit
    + add_new(current_grouped, row)
    + add_to(current_grouped, row)
    + add_all(current_grouped, rows)
}

class KeepLeastKAction {
    + add_new(current_grouped, row)
    + add_to(current_grouped, row)
    + add_all(current_grouped, rows)
}

class KeepAscOrDescK {
    - limit
    - comp_key
    - comp_key2
    + add_new(current_grouped, row)
    + add_to(current_grouped, row)
    + add_all(current_grouped, rows)
}

RowGrouper *-- RowGrouperAction

RowGrouperAction <|-- KeepAllRowsAction
RowGrouperAction <|-- KeepTopAction
RowGrouperAction <|-- KeepTopKAction
RowGrouperAction <|-- KeepLeastKAction
RowGrouperAction <|-- KeepAscOrDescK

abstract class RowGrouperAction {
    + add_new(current_grouped, row)
    + add_to(current_grouped, row)
    + add_all(current_grouped, rows)
}

class RowGrouper {
    - grouper
    + new_group_acc(row)
    + add_group_acc(acc, row)
    + add_all_group_acc(acc, rows)
    + iterate_rows(acc)
}

@enduml