@startuml

participant JoinNode
participant MiddlewareJoin
participant JoinTaskDTO
participant ResultsStorage

MiddlewareJoin -> JoinNode : handle(task)
activate JoinNode

JoinNode->JoinNode: execute(task)
activate JoinNode

JoinNode -> JoinTaskDTO: get_right_files()
activate JoinTaskDTO
JoinTaskDTO --> JoinNode : ["rfile1", "rfile2"]
deactivate JoinTaskDTO


JoinNode -> JoinTaskDTO: get_left_files()
activate JoinTaskDTO
JoinTaskDTO --> JoinNode : ["lfile1", "lfile2"]
deactivate JoinTaskDTO

JoinNode-> MiddlewareJoin : stream_files(["lfile1","lfile2"])
activate MiddlewareJoin
MiddlewareJoin -> ResultsStorage: create_stream(["lfile1", "lfile2"])
activate ResultsStorage
ResultsStorage --> MiddlewareJoin: left_join_stream
deactivate ResultsStorage
MiddlewareJoin --> JoinNode: left_join_stream
deactivate MiddlewareJoin


JoinNode-> MiddlewareJoin : stream_files(["rfile1","rfile2"])
activate MiddlewareJoin
MiddlewareJoin --> JoinNode: right_join_stream
deactivate MiddlewareJoin

JoinNode->JoinNode: join_streams(left_join_stream, right_join_stream)

JoinNode->MiddlewareJoin: save_result(joined_stream, task.output_file)
activate MiddlewareJoin
MiddlewareJoin -> ResultsStorage: save_stream(stream, file)
activate ResultsStorage
ResultsStorage --> MiddlewareJoin:
deactivate ResultsStorage
MiddlewareJoin --> JoinNode: return
deactivate MiddlewareJoin
deactivate JoinNode
deactivate JoinNode

@enduml