@startuml

participant JoinNode
participant Middleware
participant TypeHandler

activate JoinNode

Middleware -> JoinNode: handle(task)
activate JoinNode
activate Middleware

JoinNode-> JoinNode: getHandler(task.type_query)
JoinNode-> TypeHandler : exec(task.data)
activate TypeHandler

TypeHandler->Middleware: markPartitionEnd(task.query_id, task.partition)
activate Middleware
Middleware --> TypeHandler : true 
deactivate Middleware

alt All partitions reached EOF
    TypeHandler -> TypeHandler : startJoin()
    TypeHandler --> JoinNode: task_output
else Partitions left
    TypeHandler --> JoinNode : None
end
deactivate TypeHandler
deactivate JoinNode

@enduml