@startuml

participant GroupbyNode
participant Middleware
participant TypeHandler
participant TopKQueue
participant Middleware as MiddlewareTopK
participant TopKNode
activate TopKNode
activate GroupbyNode

Middleware -> GroupbyNode: handle(task)
activate GroupbyNode
activate Middleware

GroupbyNode-> GroupbyNode: getHandler(task.type_query)
GroupbyNode-> TypeHandler : exec(task.data)
activate TypeHandler
TypeHandler --> GroupbyNode: (task_output, hash_key)
deactivate TypeHandler

GroupbyNode -> Middleware: sendOut(hash_key, task_output)
activate Middleware


Middleware->Middleware: hash(hash_key)
Middleware -> TopKQueue: push_to(hashed_key, task_output)

Middleware -->GroupbyNode: 
deactivate Middleware
GroupbyNode --> Middleware :
deactivate GroupbyNode
deactivate Middleware


TopKQueue -> MiddlewareTopK: notify not empty
activate MiddlewareTopK

MiddlewareTopK -> TopKNode : handleTask(task)
activate TopKNode

TopKNode->TopKNode: execute(task)
TopKNode--> MiddlewareTopK :
deactivate MiddlewareTopK
deactivate TopKNode


@enduml