@startuml

skinparam backgroundColor transparent
skinparam shadowing false

skinparam defaultFontColor #121617
skinparam ArrowColor #121617

skinparam SequenceLifelineBorderColor #121617
skinparam SequenceActivationBorderColor #121617

skinparam EntityBorderColor #a9d4f1
skinparam ControlBackgroundColor #a9d4f1
skinparam ParticipantBackgroundColor #a9d4f1
skinparam QueueBackgroundColor #a9d4f1
skinparam RectangleBackgroundColor #a9d4f1

skinparam EntityBorderColor #44a0de
skinparam ControlBorderColor #44a0de
skinparam ParticipantBorderColor #44a0de
skinparam QueueBorderColor #44a0de
skinparam RectangleBorderColor #44a0de


control FilterNode
participant Middleware
participant TypeHandler
queue GroupbyQueue
control GroupbyNode

activate GroupbyNode
activate FilterNode

FilterNode-> Middleware : consume_filter_tasks(handler)
activate Middleware
GroupbyNode-> Middleware : consume_groupby_tasks(handler, indice)
activate Middleware
Middleware-->FilterNode: 

Middleware-->GroupbyNode: 
deactivate Middleware
deactivate Middleware


Middleware -> FilterNode: handle(task)
activate FilterNode
activate Middleware

FilterNode-> FilterNode: get_handler(task.type_query)
FilterNode-> TypeHandler : exec(task.data)
activate TypeHandler
TypeHandler --> FilterNode: task_output
deactivate TypeHandler

FilterNode -> Middleware: send_output(task_output.query_id, task_output)
activate Middleware

Middleware->Middleware: hash(key)
Middleware -> GroupbyQueue: push_to(hashed_id, task_output)

Middleware -->FilterNode: 
deactivate Middleware
FilterNode --> Middleware: return
deactivate FilterNode
deactivate Middleware


GroupbyQueue -> Middleware: notify_not_empty
activate Middleware

Middleware -> GroupbyNode : handle_groupby(task)
activate GroupbyNode

GroupbyNode->GroupbyNode: exec(task.data)
GroupbyNode--> Middleware:
deactivate Middleware
deactivate GroupbyNode


@enduml