@startuml

skinparam backgroundColor transparent
skinparam shadowing false

skinparam defaultFontColor #121617
skinparam ArrowColor #121617

skinparam SequenceLifelineBorderColor #121617
skinparam SequenceActivationBorderColor #121617

skinparam EntityBorderColor #a9d4f1
skinparam ControlBackgroundColor #a9d4f1
skinparam ParticipantBackgroundColor #a9d4f1
skinparam QueueBackgroundColor #a9d4f1
skinparam RectangleBackgroundColor #a9d4f1

skinparam EntityBorderColor #44a0de
skinparam ControlBorderColor #44a0de
skinparam ParticipantBorderColor #44a0de
skinparam QueueBorderColor #44a0de
skinparam RectangleBorderColor #44a0de


control JoinNode
participant Middleware
participant TypeHandler

activate JoinNode

Middleware -> JoinNode: handle(task)
activate JoinNode
activate Middleware

JoinNode-> JoinNode: get_handler(task.type_query)
JoinNode-> TypeHandler : exec(task.data)
activate TypeHandler

TypeHandler->Middleware: mark_partition_end(task.query_id, task.partition)
activate Middleware
Middleware --> TypeHandler : true
deactivate Middleware

alt All partitions reached EOF
    TypeHandler -> TypeHandler : start_join()
    TypeHandler --> JoinNode: task_output
else Partitions left to process
    TypeHandler --> JoinNode : none
end
deactivate TypeHandler
deactivate JoinNode

@enduml