@startuml

skinparam backgroundColor transparent
skinparam shadowing false

skinparam defaultFontColor #121617
skinparam ArrowColor #121617

skinparam SequenceLifelineBorderColor #121617
skinparam SequenceActivationBorderColor #121617

skinparam EntityBorderColor #a9d4f1
skinparam ControlBackgroundColor #a9d4f1
skinparam ParticipantBackgroundColor #a9d4f1
skinparam QueueBackgroundColor #a9d4f1
skinparam RectangleBackgroundColor #a9d4f1

skinparam EntityBorderColor #44a0de
skinparam ControlBorderColor #44a0de
skinparam ParticipantBorderColor #44a0de
skinparam QueueBorderColor #44a0de
skinparam RectangleBorderColor #44a0de


control SelectNode
participant Middleware
participant TypeHandler
queue GroupQueue
control GroupNode

activate GroupNode
activate SelectNode

SelectNode-> Middleware : consume_select_tasks(handler)
activate Middleware
GroupNode-> Middleware : consume_group_tasks(handler, indice)
activate Middleware
Middleware-->SelectNode:

Middleware-->GroupNode:
deactivate Middleware
deactivate Middleware


Middleware -> SelectNode: handle(task)
activate SelectNode
activate Middleware

SelectNode-> SelectNode: get_handler(task.type_query)
SelectNode-> TypeHandler : exec(task.data)
activate TypeHandler
TypeHandler --> SelectNode: task_output
deactivate TypeHandler

SelectNode -> Middleware: send_output(task_output.query_id, task_output)
activate Middleware

Middleware->Middleware: hash(key)
Middleware -> GroupQueue: push_to(hashed_id, task_output)

Middleware -->SelectNode:
deactivate Middleware
SelectNode --> Middleware: return
deactivate SelectNode
deactivate Middleware


GroupQueue -> Middleware: notify_not_empty
activate Middleware

Middleware -> GroupNode: handle_group(task)
activate GroupNode

GroupNode->GroupNode: exec(task.data)
GroupNode--> Middleware:
deactivate Middleware
deactivate GroupNode


@enduml