@startuml

participant Scheduler
participant Middleware
participant PlanQueue
participant JoinQueue
participant MiddlewareJoin
participant JoinNode
activate JoinNode
activate Scheduler

Scheduler-> Middleware : consume_plan_updates(handler)
activate Middleware
JoinNode-> MiddlewareJoin : consume_join_tasks(handler)
activate MiddlewareJoin
Middleware-->Scheduler: 
deactivate Middleware

MiddlewareJoin-->JoinNode: 
deactivate MiddlewareJoin

Scheduler-> Middleware : schedule_join_task(task)
activate Middleware

Middleware -> JoinQueue: push(task)

Middleware-->Scheduler: 
deactivate Middleware

JoinQueue -> MiddlewareJoin: notify_not_empty()
activate MiddlewareJoin

MiddlewareJoin -> JoinNode : handle_task(join_task)
activate JoinNode

JoinNode->JoinNode: execute(task)

JoinNode->MiddlewareJoin: notify_finished_task(task)
activate MiddlewareJoin
MiddlewareJoin -> PlanQueue: push(plan_update)
MiddlewareJoin --> JoinNode: 
deactivate MiddlewareJoin

JoinNode --> MiddlewareJoin: 
deactivate JoinNode
deactivate MiddlewareJoin


PlanQueue -> Middleware: notify_not_empty()
activate Middleware

Middleware->Scheduler: handle_update_plan(event)
activate Scheduler
Scheduler->Scheduler: check_plan_status

Scheduler-> Middleware: schedule_sort_task(task)
activate Middleware
Middleware -> Middleware: push(task)
Middleware-->Scheduler: return
deactivate Middleware
deactivate Middleware
deactivate Scheduler



@enduml